# app/services/time_policy.py

OFFER_ACCEPT_TIMEOUT_SECONDS = 60

BATCH_FILL_TIMEOUT_MINUTES = 90
BATCH_ASSIGNMENT_TIMEOUT_MINUTES = 45

PRIORITY_ASSIGNMENT_TIMEOUT_MINUTES = 20

LOADING_TIMEOUT_MINUTES = 45

LATE_ARRIVAL_ALERT_MINUTES = 90
DELIVERY_TIMEOUT_HOURS = 6