# app/services/time_policy.py

OFFER_ACCEPT_TIMEOUT_SECONDS = 60

BATCH_FILL_TIMEOUT_MINUTES = 90
BATCH_ASSIGNMENT_TIMEOUT_MINUTES = 45

PRIORITY_ASSIGNMENT_TIMEOUT_MINUTES = 20

LOADING_TIMEOUT_MINUTES = 45

LATE_ARRIVAL_ALERT_MINUTES = 20
DELIVERY_TIMEOUT_HOURS = 6

OFFER_TIMEOUT_BLACKLIST_MINUTES = 5
OFFER_EXPIRY_ALERT_AFTER_FAILURES = 3

LOCATION_STALE_AFTER_MINUTES = 3

PRIORITY_ASSIGNMENT_TIMEOUT_MINUTES = 20