"""create operation alerts table

Revision ID: 52c4f740c70c
Revises: a1217e241238
Create Date: 2026-05-01 18:22:42.419276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c4f740c70c'
down_revision: Union[str, Sequence[str], None] = 'a1217e241238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('tanker_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_alerts_alert_type'), 'operation_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_operation_alerts_batch_id'), 'operation_alerts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_operation_alerts_created_at'), 'operation_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_alerts_id'), 'operation_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_operation_alerts_job_id'), 'operation_alerts', ['job_id'], unique=False)
    op.create_index(op.f('ix_operation_alerts_job_type'), 'operation_alerts', ['job_type'], unique=False)
    op.create_index(op.f('ix_operation_alerts_request_id'), 'operation_alerts', ['request_id'], unique=False)
    op.create_index(op.f('ix_operation_alerts_severity'), 'operation_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_operation_alerts_status'), 'operation_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_operation_alerts_tanker_id'), 'operation_alerts', ['tanker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_alerts_tanker_id'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_status'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_severity'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_request_id'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_job_type'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_job_id'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_id'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_created_at'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_batch_id'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_alert_type'), table_name='operation_alerts')
    op.drop_table('operation_alerts')
    # ### end Alembic commands ###
