"""clean initial schema

Revision ID: 916132b376a8
Revises: 
Create Date: 2026-05-01 09:42:28.303947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916132b376a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('admin_identifier', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_entity_id'), 'admin_audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_entity_type'), 'admin_audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('liquids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_hazardous', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquids_id'), 'liquids', ['id'], unique=False)
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_notification_subscriptions_id'), 'notification_subscriptions', ['id'], unique=False)
    op.create_table('tankers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('tank_plate_number', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_location_update_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_request_id', sa.Integer(), nullable=True),
    sa.Column('paused_until', sa.DateTime(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('pending_offer_type', sa.String(), nullable=True),
    sa.Column('pending_offer_id', sa.Integer(), nullable=True),
    sa.Column('offer_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tank_plate_number')
    )
    op.create_index(op.f('ix_tankers_id'), 'tankers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('liquid_id', sa.Integer(), nullable=True),
    sa.Column('current_volume', sa.Float(), nullable=True),
    sa.Column('target_volume', sa.Float(), nullable=True),
    sa.Column('volume_liters', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('tanker_id', sa.Integer(), nullable=True),
    sa.Column('assignment_started_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_failed_at', sa.DateTime(), nullable=True),
    sa.Column('loading_deadline', sa.DateTime(), nullable=True),
    sa.Column('delivering_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('search_radius_km', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('last_radius_expansion_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_table('driver_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanker_id', sa.Integer(), nullable=False),
    sa.Column('offers_total', sa.Integer(), nullable=False),
    sa.Column('accepts_total', sa.Integer(), nullable=False),
    sa.Column('declines_total', sa.Integer(), nullable=False),
    sa.Column('timeouts_total', sa.Integer(), nullable=False),
    sa.Column('completed_total', sa.Integer(), nullable=False),
    sa.Column('cancelled_total', sa.Integer(), nullable=False),
    sa.Column('priority_offers_total', sa.Integer(), nullable=False),
    sa.Column('priority_accepts_total', sa.Integer(), nullable=False),
    sa.Column('priority_completed_total', sa.Integer(), nullable=False),
    sa.Column('avg_response_seconds', sa.Float(), nullable=False),
    sa.Column('jobs_completed_today', sa.Integer(), nullable=False),
    sa.Column('earnings_today', sa.Float(), nullable=False),
    sa.Column('timeout_count_today', sa.Integer(), nullable=False),
    sa.Column('decline_count_today', sa.Integer(), nullable=False),
    sa.Column('last_offered_at', sa.DateTime(), nullable=True),
    sa.Column('last_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('last_completed_at', sa.DateTime(), nullable=True),
    sa.Column('reliability_score_cached', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tanker_id')
    )
    op.create_index(op.f('ix_driver_metrics_id'), 'driver_metrics', ['id'], unique=False)
    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanker_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('zone_key', sa.String(), nullable=True),
    sa.Column('estimated_distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_eta_minutes', sa.Float(), nullable=True),
    sa.Column('offered_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_type', sa.String(), nullable=True),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('response_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_id'), 'job_offers', ['id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('liquid_id', sa.Integer(), nullable=False),
    sa.Column('volume_liters', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('delivery_type', sa.String(), nullable=False),
    sa.Column('is_asap', sa.Boolean(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_offer_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_failed_reason', sa.String(), nullable=True),
    sa.Column('assignment_started_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_failed_at', sa.DateTime(), nullable=True),
    sa.Column('refund_eligible', sa.Boolean(), nullable=False),
    sa.Column('loading_deadline', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('delivering_started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_table('batch_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('volume_liters', sa.Integer(), nullable=True),
    sa.Column('requested_volume', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('payment_deadline', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('customer_confirmed', sa.Boolean(), nullable=True),
    sa.Column('customer_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_code', sa.String(), nullable=True),
    sa.Column('refund_status', sa.String(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_reference', sa.String(), nullable=True),
    sa.Column('refund_failure_reason', sa.String(), nullable=True),
    sa.Column('refund_requested_at', sa.DateTime(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_reference')
    )
    op.create_index(op.f('ix_batch_members_id'), 'batch_members', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('tanker_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('delivery_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('tanker_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stop_order', sa.Integer(), nullable=True),
    sa.Column('planned_liters', sa.Float(), nullable=False),
    sa.Column('actual_liters_delivered', sa.Float(), nullable=True),
    sa.Column('meter_start_reading', sa.Float(), nullable=True),
    sa.Column('meter_end_reading', sa.Float(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('measurement_required', sa.Boolean(), nullable=False),
    sa.Column('measurement_valid', sa.Boolean(), nullable=False),
    sa.Column('anomaly_flagged', sa.Boolean(), nullable=False),
    sa.Column('anomaly_reason', sa.String(), nullable=True),
    sa.Column('otp_required', sa.Boolean(), nullable=False),
    sa.Column('otp_verified', sa.Boolean(), nullable=False),
    sa.Column('otp_verified_at', sa.DateTime(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_consumed_at', sa.DateTime(), nullable=True),
    sa.Column('otp_invalid_attempts', sa.Integer(), nullable=False),
    sa.Column('delivery_code', sa.String(), nullable=True),
    sa.Column('customer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('customer_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('measurement_started_at', sa.DateTime(), nullable=True),
    sa.Column('measurement_completed_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('skipped_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('photo_proof_url', sa.String(), nullable=True),
    sa.Column('batch_member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['batch_member_id'], ['batch_members.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['batch_members.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_records_id'), 'delivery_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_records_id'), table_name='delivery_records')
    op.drop_table('delivery_records')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_batch_members_id'), table_name='batch_members')
    op.drop_table('batch_members')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_job_offers_id'), table_name='job_offers')
    op.drop_table('job_offers')
    op.drop_index(op.f('ix_driver_metrics_id'), table_name='driver_metrics')
    op.drop_table('driver_metrics')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tankers_id'), table_name='tankers')
    op.drop_table('tankers')
    op.drop_index(op.f('ix_notification_subscriptions_id'), table_name='notification_subscriptions')
    op.drop_table('notification_subscriptions')
    op.drop_index(op.f('ix_liquids_id'), table_name='liquids')
    op.drop_table('liquids')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_entity_type'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_entity_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
